"""grounding — the shared train==serve contract. Import from grounding.contract."""
from .contract import (  # noqa: F401
    CONTRACT_VERSION,
    EXAMPLE_TYPES,
    ANSWER_TYPES,
    SYSTEM_PROMPT,
    TOOLS,
    TOOL_NAMES,
    Vehicle,
    Record,
    citation,
    cross_vehicle_answer,
    figure_answer,
    REFUSAL_TEMPLATE,
    ELICITATION_TEMPLATE,
    system_msg,
    user_msg,
    assistant_tool_call,
    tool_result,
    assistant_answer,
    call_id,
    make_record,
    validate_messages,
)
